### ISSUE TITLE
sh: nodemon: command not found

### ISSUE THREAD

**Issue by ghost** [xSequential/Exercise-Template-Node-React-Mongo#1]
```
$ nodemon --exec babel-node server.js --ignore assets/
sh: nodemon: command not found
```

It's a good idea to add nodemon as a dev dependency into the project.
I don't have nodemon globally in my system and I don't want to install anything globally.

**Comment by tripndots** [comment]
Good call, I will commit a fix today.

**Comment by tripndots** [comment]
@serge-nikitin  The package.json files have been updated, thank you for your input
